### ISSUE TITLE
Support for other SAML providers

### ISSUE THREAD

**Issue by afdecastro879** [greenpau/caddy-auth-saml#10]
Hi There!

I'm checking this project and I'm interested in using it. As you point in the documentation I'm reaching out because we will love to see support for other providers, specifically OKTA and OneLogin.

I'm also wondering:
- What avoids this plugin to have a generic SAML authentication?(I mean a generic configuration for any SAML provider) 
- What are the differences between Azure/Okta/Other that means extra work to have specific support for those? 
- I also work sometimes with non public SAML providers which I'd like to configure using this plugin as well. What are the challenges with that approach?

I'm happy to contribute on anything :)

**Comment by greenpau** [comment]
>  As you point in the documentation I'm reaching out because we will love to see support for other providers, specifically OKTA and OneLogin.

@afdecastro879 , that's the right move! :-)

> What avoids this plugin to have a generic SAML authentication?(I mean a generic configuration for any SAML provider)

Nothing really. I was focusing on Azure AD because that's what I use on a daily basis. I just don't have access to production instances of "Okta/Other".

> What are the differences between Azure/Okta/Other that means extra work to have specific support for those?

It is not a lot of work really. I think if I will revisit this I would restructure the parsing of the below. I would say each provider has it own twist on a "thing". That's why it is important to have access to a live production instance.

![image](https://user-images.githubusercontent.com/3826416/86151046-35fba380-bacc-11ea-98ec-459253aa68b5.png)

> I also work sometimes with non public SAML providers which I'd like to configure using this plugin as well. What are the challenges with that approach?

Once again, there are no challenges ... it is mainly the parsing of the config. Things like `Marshal`, `Unmarshall`, `interface{}`.

If you can get me access to a production instance, I could refactor the plugin. It was actually on my list to add this plugin to https://github.com/greenpau/caddy-auth. It is Caddy v2 "app" that centralizes the plugins.

**Comment by greenpau** [comment]
@afdecastro879 , to accommodate multiple providers I would switch to the interface I use in here https://github.com/greenpau/caddy-auth-forms/blob/master/backend.go#L66-L108. This proved to be flexible way to approach it.

**Comment by greenpau** [comment]
@afdecastro879 , fyi, I am planning to merge the functionality provided by this plugin to https://github.com/greenpau/caddy-auth-portal. That would bring in Caddyfile support and a better interface to accommodate other SAML providers.

**Comment by greenpau** [comment]
@trajche , the functionality provided by this plugin moved to [caddy-auth-portal](https://github.com/greenpau/caddy-auth-portal). Caddyfile support exists. Please migrate. If you have an issue, please open one in https://github.com/greenpau/caddy-auth-portal/issues.

Please re-open this specific issue in https://github.com/greenpau/caddy-auth-portal/issues.

**Comment by greenpau** [comment]
@afdecastro879, the functionality provided by this plugin moved to [caddy-auth-portal](https://github.com/greenpau/caddy-auth-portal). Caddyfile support exists. Please migrate. If you have an issue, please open one in https://github.com/greenpau/caddy-auth-portal/issues.

Please re-open this specific issue in https://github.com/greenpau/caddy-auth-portal/issues.
